version: 2

preset:
  image: gantry-admin://images/layouts/2-col-left.png
  name: base-layouts

layout:

  /top_panel/:

  /header_panel/:

  /content_panel/:
    -
      - sidebar 30:

      - main 70:

  /features_panel/:

  /bottom_panel/:

  /footer_panel/:

  /copyright_panel/:

  offcanvas:

structure:
  sidebar:
    subtype: aside
    block:
      fixed: 1
